const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs/promises');const path=require('node:path');const os=require('node:os');const crypto=require('node:crypto');const {buildSync}=require('esbuild');
const bundle=buildSync({entryPoints:[path.resolve('electron/direct-media.ts')],bundle:true,platform:'node',format:'cjs',write:false});const moduleObject={exports:{}};new Function('require','module','exports',bundle.outputFiles[0].text)(require,moduleObject,moduleObject.exports);const {DirectMedia}=moduleObject.exports;
const scope='a'.repeat(64),id='01234567-89ab-4cde-8fab-0123456789ab',account='11234567-89ab-4cde-8fab-0123456789ab';
async function fixture(){const root=await fs.mkdtemp(path.join(os.tmpdir(),'liteseal-direct-main-test-'));const calls=[];const bytes=Buffer.from([137,80,78,71,13,10,26,10,1,2,3]);let epoch=0,currentScope=scope,hidden=false;let destination=path.join(root,'saved.png');let beforeWrite=null;
 const info={id,peer:account,kind:'attachment',name:'中文.png',mime:'image/png',size:bytes.length,duration_ms:null,cache:'cached'};
 const bridge={call:async(name,args)=>{calls.push({name,args});if(name==='get_direct_chat')return{notification_scope:currentScope};if(name==='get_direct_media_info'){if(hidden)throw Error('hidden');return info;}if(name==='write_direct_media'){await fs.writeFile(args.path,bytes,{flag:'wx'});await beforeWrite?.();return{info,digest:crypto.createHash('sha256').update(bytes).digest('hex')};}if(name==='stage_direct_media'){const input=await fs.readFile(args.path);assert(input.length>0);return{id:args.id,phase:'staged',name:path.basename(args.path),bytes:input.length};}throw Error('unexpected fixture command');}};
 const manager=new DirectMedia(bridge,{capture:()=>epoch,check:e=>{if(e!==epoch)throw Error('changed');},temp:()=>root,open:async()=>path.join(root,'input.bin'),save:async()=>destination,clipboard:async()=>bytes});
 return{manager,root,calls,bytes,info,change:()=>{epoch++;},scope:()=>{currentScope='b'.repeat(64);},hide:()=>{hidden=true;},writeHook:f=>{beforeWrite=f;},destination:()=>destination,cleanup:async()=>{manager.invalidate();await fs.rm(root,{recursive:true,force:true});}};
}
test('opaque preview, ranges, tampering and invalidated visibility never expose file paths',async()=>{const f=await fixture();try{const url=await f.manager.run('export_direct_media',{scope,id,preview:true});assert.match(url,/^liteseal-media:\/\/preview\/[0-9a-f-]+$/);assert(!url.includes(f.root));const response=await f.manager.response(new Request(url));assert.equal(response.status,200);assert.deepEqual(Buffer.from(await response.arrayBuffer()),f.bytes);const range=await f.manager.response(new Request(url,{headers:{range:'bytes=0-3'}}));assert.equal(range.status,206);assert.equal((await range.arrayBuffer()).byteLength,4);assert.equal((await f.manager.response(new Request(url,{headers:{range:'bytes=100-'}}))).status,416);
 const written=f.calls.find(c=>c.name==='write_direct_media').args.path;await fs.writeFile(written,Buffer.alloc(f.bytes.length));assert.equal((await f.manager.response(new Request(url))).status,403);assert.equal((await f.manager.response(new Request(url))).status,404);
 const second=await f.manager.run('export_direct_media',{scope,id,preview:true});f.hide();assert.equal((await f.manager.response(new Request(second))).status,403);assert(f.calls.every(c=>!('bytes' in c.args)&&!('key' in c.args)&&!('encoded' in c.args)));}finally{await f.cleanup();}});
test('exclusive export preserves existing destination and a changed scope cannot commit',async()=>{const f=await fixture();try{await fs.writeFile(f.destination(),'original');await assert.rejects(f.manager.run('export_direct_media',{scope,id}),/EEXIST|exist/);assert.equal(await fs.readFile(f.destination(),'utf8'),'original');await fs.unlink(f.destination());f.writeHook(async()=>f.scope());await assert.rejects(f.manager.run('export_direct_media',{scope,id}));await assert.rejects(fs.stat(f.destination()),{code:'ENOENT'});assert.equal((await fs.readdir(f.root)).length,0);}finally{await f.cleanup();}});
test('recorded bytes are staged by a private temporary path and removed after IPC',async()=>{const f=await fixture();try{const blob=Uint8Array.from([0x1a,0x45,0xdf,0xa3,1,2]);await f.manager.run('stage_direct_voice',{scope,account,bytes:blob.buffer,durationMs:1000});const staged=f.calls.find(c=>c.name==='stage_direct_media');assert.equal(staged.args.kind,'voice');assert.equal(staged.args.durationMs,1000);assert(!('bytes' in staged.args));await assert.rejects(fs.stat(staged.args.path),{code:'ENOENT'});await assert.rejects(f.manager.run('stage_direct_voice',{scope,account,bytes:new ArrayBuffer(1),durationMs:60001}));await assert.rejects(f.manager.run('select_direct_media',{scope,account,path:'injected'}));}finally{await f.cleanup();}});
test('scope epoch retirement removes old previews even when an old URL is reused',async()=>{const f=await fixture();try{const url=await f.manager.run('export_direct_media',{scope,id,preview:true});f.change();assert.equal((await f.manager.response(new Request(url))).status,403);assert.equal((await f.manager.response(new Request('liteseal-media://other/'+id))).status,404);assert.equal((await f.manager.response(new Request(url,{method:'POST'}))).status,404);}finally{await f.cleanup();}});
