import {StrictMode} from "react";
import {flushSync} from "react-dom";
import {root} from "./device-harness-root";
import DirectChat from "../src/components/DirectChat";
import type {DirectSnapshot,DirectHistory,DirectPeer,DirectProgress,DirectDraft} from "../../electron/contracts";
import "../src/theme.css";
const peer:DirectPeer={account:"22222222-2222-4222-8222-222222222222",origin:"https://synthetic.example",root_device:"peer-root",root_fingerprint:"b".repeat(64),encryption_fingerprint:"c".repeat(64),signing_fingerprint:"d".repeat(64)};
let view:DirectSnapshot,rows:DirectHistory["messages"],delay=false,failPrepare=false,deferred:((p:DirectProgress)=>void)|null=null;
const calls:{name:string;args:any}[]=[];
const drafts=new Map<string,DirectDraft>();
const preferences=new Map<string,{revision:number;muted:boolean;read:number}>();
let notificationTarget:{peer:string}|null=null;
let holdDraft=false,failDraft=false,finishDraft:(()=>void)|null=null;
const draft=(account:string)=>drafts.get(account)??{peer:account,revision:0,text:"",prepared:null};
const api={
  set_direct_notification_context:async()=>{},
  take_direct_notification_target:async()=>{const target=notificationTarget;notificationTarget=null;return target;},
  get_direct_draft:async({account}:any)=>structuredClone(draft(account)),
  save_direct_draft:async(args:any)=>{calls.push({name:"draft",args});if(failDraft)throw new Error("模拟磁盘满，正文保留");if(draft(args.account).revision!==args.revision)throw new Error("草稿已变化");const next={peer:args.account,revision:args.revision+1,text:args.text,prepared:null};if(holdDraft)return new Promise<DirectDraft>(resolve=>{finishDraft=()=>{drafts.set(args.account,next);resolve(structuredClone(next));};});drafts.set(args.account,next);return structuredClone(next);},
  get_direct_chat:async()=>{const next=structuredClone(view);next.conversations=next.peers.map(p=>{const pref=preferences.get(p.account)??{revision:0,muted:false,read:0},history=rows.filter(r=>r.peer===p.account);return {peer:p.account,revision:pref.revision,muted:pref.muted,unread:history.filter(r=>r.cursor>pref.read&&r.role==="incoming"&&r.outcome==="processed").length,latest_id:history[0]?.id??null,latest_cursor:history[0]?.cursor??null,has_draft:!!draft(p.account).text};});return next;},
  get_direct_history:async({account,before}:any)=>{const page=rows.filter(r=>(!account||r.peer===account)&&(before==null||r.cursor<before)).slice(0,6);return {messages:structuredClone(page),next_cursor:page.length===6?page[5].cursor:null};},
  mark_direct_read:async({account,throughId}:any)=>{calls.push({name:"read",args:{account,throughId}});const row=rows.find(r=>r.id===throughId&&r.peer===account);if(!row)throw new Error("错误会话边界");const pref=preferences.get(account)??{revision:0,muted:false,read:0};preferences.set(account,{...pref,revision:pref.revision+1,read:Math.max(pref.read,row.cursor)});},
  set_direct_muted:async(args:any)=>{calls.push({name:"mute",args});const pref=preferences.get(args.account)??{revision:0,muted:false,read:0};if(pref.revision!==args.revision)throw new Error("会话设置已变化");preferences.set(args.account,{...pref,revision:pref.revision+1,muted:args.muted});},
  inspect_direct_peer:async(args:any)=>{calls.push({name:"inspect",args});return structuredClone(peer);},
  confirm_direct_peer:async(args:any)=>{calls.push({name:"confirm",args});view.peers=[structuredClone(peer)];},
  prepare_direct_text:async(args:any)=>{calls.push({name:"prepare",args});if(draft(args.account).revision!==args.draftRevision||draft(args.account).text!==args.text)throw new Error("未保存草稿");drafts.set(args.account,{peer:args.account,revision:args.draftRevision+1,text:"",prepared:"original-send"});view.tasks=[{id:"original-send",revision:1,state:"prepared",peer:peer.account,epoch:"e".repeat(64),digest:[],cancel_requested:false}];if(failPrepare)throw new Error("原准备响应丢失");return {task:structuredClone(view.tasks[0]),condition:"prepared" as const,http_status:null};},
  direct_task_step:async(args:any)=>{calls.push({name:"step",args});if(delay)return new Promise<DirectProgress>(r=>{deferred=r;});return {task:structuredClone(view.tasks[0]),condition:"retry" as const,http_status:null};},
  cancel_direct_task:async(args:any)=>{calls.push({name:"cancel",args});view.tasks[0].cancel_requested=true;return structuredClone(view.tasks[0]);},
  forget_direct_task:async(args:any)=>{calls.push({name:"forget",args});view.tasks=[];},
  hide_direct_message:async(args:any)=>{calls.push({name:"hide",args});rows=rows.filter(r=>r.id!==args.id);},
};
function reset(){holdDraft=false;failDraft=false;finishDraft=null;drafts.clear();preferences.clear();failPrepare=false;view={notification_scope:"synthetic-scope",identity:{...peer,account:"11111111-1111-4111-8111-111111111111",root_fingerprint:"a".repeat(64)},device:"own-second-device",peers:[],conversations:[],tasks:[],can_network:true};rows=Array.from({length:52},(_,i)=>({cursor:52-i,id:`message-${52-i}`,sender:peer.account,sender_device:"peer-root",peer:peer.account,role:"incoming",kind:"text",outcome:"processed",sent_at:Date.now(),accepted_at:123,text:`历史 ${52-i} 中文 🦭 <script>不执行</script>`}));delay=false;calls.length=0;window.confirm=()=>true;window.desktop=new Proxy(api,{get(t,k:keyof typeof api){if(!(k in t))throw new Error("chat accessed legacy/private API "+String(k));return t[k];}}) as any;}
const sleep=()=>new Promise(r=>setTimeout(r,55));
const check=(value:unknown,message:string)=>{if(!value)throw new Error(message);};
const button=(text:string)=>[...document.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent?.trim()===text);
async function click(text:string){check(button(text),"missing chat action "+text);button(text)!.click();await sleep();}
async function fill(label:string,value:string){const node=document.querySelector<HTMLInputElement|HTMLTextAreaElement>(`[aria-label="${label}"]`)!;check(node,"missing field "+label);const prototype=node instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;Object.getOwnPropertyDescriptor(prototype,"value")!.set!.call(node,value);node.dispatchEvent(new Event("input",{bubbles:true}));await sleep();}
async function select(account:string){const node=document.querySelector<HTMLSelectElement>('[aria-label="聊天账号"]')!;node.value=account;node.dispatchEvent(new Event('change',{bubbles:true}));await sleep();}
function open(text:string){const node=[...document.querySelectorAll('summary')].find(n=>n.textContent?.startsWith(text));check(node,"missing section "+text);node!.click();}
let generation=0;const panel=()=>flushSync(()=>root.render(<StrictMode><DirectChat key={++generation}/></StrictMode>));
(window as any).runDirectTests=async()=>{
  const results:string[]=[];reset();panel();await sleep();check(!calls.length&&document.querySelectorAll('[aria-label="v3 文字历史"] li').length===6,"mount mutates task or wrong page");check(document.body.textContent!.includes("<script>")&&document.querySelectorAll('script').length===1,"text executes markup");results.push("mount reads only scoped metadata/history and renders authenticated text safely");
  for(let i=0;i<8;i++)await click("加载更早的文字");check(document.querySelectorAll('[aria-label="v3 文字历史"] li').length===52&&button("加载更早的文字")!.disabled,"52-message paging misses or duplicates records");results.push("52-message bounded paging contains each record once");
  await click("在本机隐藏");check(!rows.some(r=>r.id==="message-52")&&!document.body.textContent!.includes("历史 52 中文"),"hidden record returns");window.dispatchEvent(new Event("liteseal-direct-changed"));await sleep();check(!document.body.textContent!.includes("历史 52 中文"),"background change revives hidden record");results.push("explicit hiding and background refresh preserve visibility");
  open("核对新的聊天账号");await fill("对方账号编号",peer.account);await click("查询对方根身份");check(!calls.some(c=>c.name==="confirm")&&button("确认对方原设备根身份")!.disabled,"inspection auto-trusts root");await fill("核对对方根指纹","wrong");check(button("确认对方原设备根身份")!.disabled,"wrong root accepted");await fill("核对对方根指纹",peer.root_fingerprint);await click("确认对方原设备根身份");check(calls.find(c=>c.name==="confirm")!.args.fingerprint===peer.root_fingerprint,"confirmation replaces root");results.push("candidate inspection requires independent full fingerprint confirmation");
  await fill("v3 消息正文","重启恢复的草稿 🦭");check(draft(peer.account).text==="重启恢复的草稿 🦭","draft not persisted");panel();await sleep();await select(peer.account);check(document.querySelector<HTMLTextAreaElement>('[aria-label="v3 消息正文"]')!.value==="重启恢复的草稿 🦭","remount loses saved draft");results.push("saved draft restores on remount for the same peer and scope");
  holdDraft=true;await fill("v3 消息正文","较早保存中");await fill("v3 消息正文","保存期间更新正文");holdDraft=false;finishDraft!();await sleep();await sleep();check(draft(peer.account).text==="保存期间更新正文"&&document.querySelector<HTMLTextAreaElement>('[aria-label="v3 消息正文"]')!.value===draft(peer.account).text,"late save overrides newer edit");results.push("serialized autosave preserves edits made while an older save is in flight");
  failDraft=true;await fill("v3 消息正文","磁盘恢复后重试这段正文");check(document.body.textContent!.includes("模拟磁盘满")&&document.querySelector<HTMLTextAreaElement>('[aria-label="v3 消息正文"]')!.value==="磁盘恢复后重试这段正文","save failure loses unsaved text");failDraft=false;await click("保存此账号草稿");check(draft(peer.account).text==="磁盘恢复后重试这段正文","retry cannot save preserved text");results.push("failed write keeps local text and explicit retry resumes without discarding it");
  const before=draft(peer.account);drafts.set(peer.account,{...before,revision:before.revision+1,text:"另一操作的新正文"});await fill("v3 消息正文","本窗口未保存正文");check(draft(peer.account).text==="另一操作的新正文"&&document.querySelector<HTMLTextAreaElement>('[aria-label="v3 消息正文"]')!.value==="本窗口未保存正文","stale save overwrites remote or local draft");window.confirm=()=>false;await click("重新读取草稿");check(document.querySelector<HTMLTextAreaElement>('[aria-label="v3 消息正文"]')!.value==="本窗口未保存正文","denied reload discards text");window.confirm=()=>true;await click("重新读取草稿");check(document.querySelector<HTMLTextAreaElement>('[aria-label="v3 消息正文"]')!.value==="另一操作的新正文","explicit reload fails");results.push("stale revision preserves both drafts and reload needs explicit consent");
  const other={...peer,account:"33333333-3333-4333-8333-333333333333"};view.peers.push(other);await click("刷新文字历史");await select(other.account);await fill("v3 消息正文","另一个账号的独立草稿");await select(peer.account);check(document.querySelector<HTMLTextAreaElement>('[aria-label="v3 消息正文"]')!.value==="另一操作的新正文"&&draft(other.account).text==="另一个账号的独立草稿","peer switch mixes drafts");results.push("peer switch flushes and restores independent draft bodies");
  failPrepare=true;await fill("v3 消息正文","待发中文 🦭");await click("发送加密文字");check(button("发送加密文字")!.disabled&&view.tasks[0].id==="original-send"&&document.body.textContent!.includes("原准备响应丢失"),"lost preparation permits replacement task");results.push("lost preparation response queries original tasks and blocks replacement send");
  failPrepare=false;view.tasks=[];await click("刷新文字历史");await fill("v3 消息正文","新的待发正文");await click("发送加密文字");check(calls.find(c=>c.name==="step")!.args.id==="original-send"&&document.querySelector<HTMLTextAreaElement>('[aria-label="v3 消息正文"]')!.value==="","send changes original id or retains committed draft");check(document.body.textContent!.includes("原结果尚未确认"),"unknown send reports success");results.push("text sends original persisted id and preserves unknown outcome");
  open("原发送任务");delay=true;button("继续原发送任务")!.click();await sleep();check(!button("取消原发送任务")!.disabled,"in-flight retry prevents cancel");await click("取消原发送任务");deferred!({task:{...view.tasks[0],state:"accepted"},condition:"accepted",http_status:null});await sleep();check(!document.body.textContent!.includes("服务端已接受原消息"),"late success overrides cancel intent");results.push("cancel while retrying rejects late UI success");
  reset();view.peers=[peer];view.tasks=[{id:"original-send",revision:2,state:"publishing",peer:peer.account,epoch:"e",digest:[],cancel_requested:false}];panel();await sleep();open("原发送任务");delay=true;button("继续原发送任务")!.click();await sleep();window.dispatchEvent(new Event("liteseal-app-locked"));deferred!({task:{...view.tasks[0],state:"accepted"},condition:"accepted",http_status:null});await sleep();check(!document.body.textContent!.includes("历史 52")&&!document.querySelector('[aria-label="v3 消息正文"]')&&!document.body.textContent!.includes("服务端已接受"),"lock exposes history or accepts late response");results.push("lock clears identity, text and history and rejects late results");
  reset();view.can_network=false;panel();await sleep();open("核对新的聊天账号");await fill("对方账号编号",peer.account);check(button("查询对方根身份")!.disabled&&button("发送加密文字")!.disabled&&document.querySelectorAll('[aria-label="v3 文字历史"] li').length===6,"signed-out view networks or hides readable history");results.push("signed-out scope retains local history and blocks network actions");
  reset();view.peers=[peer,other];rows.unshift({...rows[0],peer:other.account,sender:other.account,id:"other-message",cursor:53,text:"其他会话正文"});panel();await sleep();await select(peer.account);check(!document.querySelector('[aria-label="v3 文字历史"]')!.textContent!.includes("其他会话正文")&&document.querySelectorAll('[aria-label="v3 文字历史"] li').length===6,"selected peer includes other history or page is short");results.push("selected peer filters before paging and switching clears old rows");
  rows.unshift({...rows[1],id:"late-message",cursor:54,text:"查询后到达的新正文"});await click("将此页及更早消息标记已读");check(preferences.get(peer.account)!.read===52&&document.body.textContent!.includes("此会话未读 1"),"read action consumes later arrival or clears another peer");check(!preferences.has(other.account),"read marker crosses peer");results.push("read action uses displayed boundary and preserves a later incoming message");
  await click("静音此会话");check(preferences.get(peer.account)!.muted&&button("取消此会话静音"),"mute setting not reflected");panel();await sleep();await select(peer.account);check(button("取消此会话静音"),"remount loses muted state");const pref=preferences.get(peer.account)!;preferences.set(peer.account,{...pref,revision:pref.revision+1});await click("取消此会话静音");check(preferences.get(peer.account)!.muted&&document.body.textContent!.includes("会话设置已变化"),"stale preference overwrites current state");results.push("mute survives remount and stale revision cannot overwrite it");
  notificationTarget={peer:other.account};window.dispatchEvent(new Event("liteseal-direct-notification-target"));await sleep();await sleep();check(document.querySelector<HTMLSelectElement>('[aria-label="聊天账号"]')!.value===other.account&&document.querySelector('[aria-label="v3 文字历史"]')!.textContent!.includes("其他会话正文")&&!document.querySelector('[aria-label="v3 文字历史"]')!.textContent!.includes("历史 52"),"notification target routes mixed history");results.push("fixed notification click event selects only the matching scoped conversation");return results;
};
(window as any).showDirectChat=async()=>{reset();view.peers=[peer];panel();for(let i=0;i<20;i++){await sleep();if(button("刷新文字历史")&&!button("刷新文字历史")!.disabled&&document.querySelector<HTMLTextAreaElement>('[aria-label="v3 消息正文"]')?.value==="")return;}throw new Error("capture did not reach fresh scoped view");};
