import {flushSync} from "react-dom";
import {root} from "./device-harness-root";
import "../src/components/direct-chat.css";
import {HistoryTransfers} from "../src/components/HistoryTransfers";
import {TransferredHistory} from "../src/components/TransferredHistory";
import type {DirectHistory,HistoryTransfer,TransferredRecord} from "../../electron/contracts";
const scope="a".repeat(64),account="22222222-2222-4222-8222-222222222222",target="33333333-3333-4333-8333-333333333333",id="44444444-4444-4444-8444-444444444444";
let calls:{name:string;args:any}[]=[],transfers:HistoryTransfer[]=[],copies:TransferredRecord[]=[],lost=false,unknown=false,delay=false,finish:((value:any)=>void)|null=null,confirmed=true;
const originals:DirectHistory["messages"]=[{cursor:1,id,sender:account,sender_device:"peer-root",peer:account,role:"incoming",kind:"text",outcome:"processed",sent_at:Date.now(),accepted_at:Date.now(),text:"中文 🦭 指定历史",operation_revision:0}, {cursor:2,id:"55555555-5555-4555-8555-555555555555",sender:account,sender_device:"peer-root",peer:account,role:"incoming",kind:"text",outcome:"retracted",sent_at:Date.now(),accepted_at:Date.now(),text:null,retracted:true,operation_revision:1}];
const copied=(patch:Partial<TransferredRecord>={}):TransferredRecord=>({id,peer:account,sender:account,sender_device:"peer-root",sent_at:Date.now(),accepted_at:Date.now(),operation_revision:1,retracted:false,kind:"text",text:"受信迁移 中文 🦭 <img onerror=bad>",media:null,transfer:target,verification:"authorized_history_transfer",...patch});
const targets=[{device:target,encryption_fingerprint:"b".repeat(64),signing_fingerprint:"c".repeat(64)}];
let relaySteps=0,receiveSteps=0;
let relayJobs:any[]=[],receiving:any[]=[];
const api={
  set_direct_history_pause:async(args:any)=>{calls.push({name:"pause",args});if(args.receive)receiving=receiving.map(r=>({...r,revision:r.revision+1,paused:args.paused,abandoned:args.abandon||args.paused&&r.abandoned,downloaded:args.abandon?0:r.downloaded}));else relayJobs=relayJobs.map(j=>({...j,revision:j.revision+1,paused:args.paused}));},
  direct_history_relay_step:async(args:any)=>{calls.push({name:"relay",args});relaySteps++;return{id:args.id,digest:[],state:relaySteps===1?"staging":"ready",next:1};},
  cancel_direct_history_relay:async(args:any)=>{calls.push({name:"relay-cancel",args});return{id:args.id,digest:[],state:"cancelled",next:0};},
  receive_direct_history_relay:async(args:any)=>{calls.push({name:"receive",args});receiveSteps++;return{id:target,downloaded:Math.min(receiveSteps,2),total:2,imported:receiveSteps>=3};},
  get_direct_history_transfers:async()=>{if(delay)return new Promise(r=>{finish=r;});return{targets,transfers:structuredClone(transfers),relay_jobs:structuredClone(relayJobs),receiving:structuredClone(receiving)};},
  get_transferred_history:async(args:any)=>{calls.push({name:"read",args});return{messages:structuredClone(copies),next_cursor:null};},
  get_backup_transferred_history:async(args:any)=>{calls.push({name:"archive-read",args});return{messages:structuredClone(copies),next_cursor:null};},
  prepare_direct_history_transfer:async(args:any)=>{calls.push({name:"prepare",args});if(unknown){unknown=false;throw new Error("尚未确认原准备");}const row:HistoryTransfer={id:args.id,revision:1,state:"prepared",peer:args.account,source_device:"own-root",target_device:args.target,selected:args.selection.length,created_at:args.createdAt,expires_at:args.createdAt+600000,digest:[],bytes:100};transfers=[row];if(lost){lost=false;throw new Error("准备成功但回包丢失");}return row;},
  cancel_direct_history_transfer:async(args:any)=>{calls.push({name:"cancel",args});transfers=transfers.map(t=>({...t,revision:t.revision+1,state:"cancelled"}));return transfers[0];},
  export_direct_history_transfer:async(args:any)=>{calls.push({name:"export",args});return"已保存";},
  import_direct_history_transfer:async(args:any)=>{calls.push({name:"import",args});return null;},
  hide_transferred_message:async(args:any)=>{calls.push({name:"hide",args});copies=copies.filter(c=>c.id!==args.id);},
  export_transferred_media:async(args:any)=>{calls.push({name:"media",args});return"saved";},
  export_backup_transferred_media:async(args:any)=>{calls.push({name:"archive-media",args});return"saved";},
};
window.desktop=api as any;window.confirm=()=>confirmed;
const sleep=()=>new Promise(r=>setTimeout(r,35));const check=(ok:any,why:string)=>{if(!ok)throw new Error(why);};
function render(archive=false){flushSync(()=>root.render(<div className="direct-chat">{archive?<TransferredHistory archive={target} account={account}/>:<HistoryTransfers scope={scope} account={account} originals={originals} online/>}</div>));}
function button(text:string){return [...document.querySelectorAll<HTMLButtonElement>("button")].find(b=>b.textContent?.trim()===text);}
async function click(text:string){const el=button(text);check(el&&!el.disabled,"missing or disabled: "+text);el!.click();await sleep();await sleep();}
async function choose(){const select=document.querySelector<HTMLSelectElement>('[aria-label="历史授权目标"]')!;select.value=target;select.dispatchEvent(new Event("change",{bubbles:true}));await sleep();document.querySelector<HTMLInputElement>('fieldset input')!.click();await sleep();}
function reset(){relaySteps=0;receiveSteps=0;relayJobs=[];receiving=[];flushSync(()=>root.render(null));calls=[];transfers=[];copies=[];lost=false;unknown=false;delay=false;finish=null;confirmed=true;}
(window as any).runHistoryTransferTests=async()=>{
  const results:string[]=[];reset();render();await sleep();await sleep();
  check(button("保存选定历史授权")?.disabled,"unselected history can be authorized");check(!calls.some(c=>c.name==="prepare"),"join implicitly grants history");check(document.querySelectorAll('fieldset input').length===2,"confirmed selection missing");results.push("default has no implicit history grant and only explicit confirmed selection is offered");
  await choose();confirmed=false;await click("保存选定历史授权");check(!calls.some(c=>c.name==="prepare"),"canceled confirmation prepared");confirmed=true;lost=true;await click("保存选定历史授权");const prepared=calls.find(c=>c.name==="prepare")!.args;check(prepared.selection.length===1&&prepared.selection[0]===id,"selection broadened");check(!("text" in prepared)&&!("key" in prepared),"secret or plaintext added to grant intent");check(button("保存原授权文件"),"lost reply cannot recover stored original");results.push("explicit device and IDs, confirmation cancel and preparation reply loss preserve the original task");
  await click("保存原授权文件");check(calls.find(c=>c.name==="export")?.args.id===prepared.id,"export creates a new grant");await click("查询或继续原授权中继");check(calls.filter(c=>c.name==="relay").length===2&&calls.filter(c=>c.name==="relay").every(c=>c.args.id===prepared.id&&c.args.revision===1),"relay regenerated original grant");await click("取消原授权中继");check(calls.find(c=>c.name==="relay-cancel")?.args.id===prepared.id,"relay cancellation changed ID");results.push("explicit relay advances original chunks and preserves its ID on cancellation");await click("停止本机导出");check(transfers[0].state==="cancelled"&&!button("保存原授权文件"),"stop permits output");results.push("original export and stop retain task ID without claiming remote erasure");
  reset();unknown=true;render();await sleep();await sleep();await choose();await click("保存选定历史授权");const first=calls.find(c=>c.name==="prepare")!.args;check(button("查询或继续原历史准备"),"unknown preparation cannot continue");await click("查询或继续原历史准备");const retry=calls.filter(c=>c.name==="prepare")[1].args;check(JSON.stringify(first)===JSON.stringify(retry),"unknown request regenerated");results.push("unknown unstored preparation retries the exact same intent and UUID");
  reset();copies=[copied(),copied({id:"66666666-6666-4666-8666-666666666666",retracted:true,text:null}),copied({id:"77777777-7777-4777-8777-777777777777",kind:"attachment",text:null,media:{name:"complete.txt",mime:"text/plain",size:12,duration_ms:null,cached:true}}),copied({id:"88888888-8888-4888-8888-888888888888",kind:"attachment",text:null,media:{name:"missing.txt",mime:"text/plain",size:12,duration_ms:null,cached:false}})];render(true);await sleep();await sleep();
  check(document.body.textContent?.includes("受信原设备迁移")&&document.body.textContent?.includes("消息已撤回"),"trusted source/retraction absent");check(!document.querySelector("img"),"copied text interpreted as HTML");check(!button("隐藏授权副本")&&!button("保存选定历史授权"),"archive exposes mutations");check([...document.querySelectorAll("button")].filter(b=>b.textContent==="保存迁移附件").length===1,"missing cache exposes media output");await click("保存迁移附件");check(calls.find(c=>c.name==="archive-media")?.args.id===target,"archive handle missing");results.push("offline copies are labeled, plaintext stays text, retractions hide body and only complete cached media can be saved");
  reset();render();await sleep();await sleep();await click("接收原设备中继授权");check(calls.filter(c=>c.name==="receive").length===3&&calls.filter(c=>c.name==="receive").every(c=>c.args.scope===scope),"relay receive scope/progress missing");results.push("explicit relay receive advances bounded chunks before confirmed history");reset();copies=[copied()];render();await sleep();await sleep();await click("隐藏授权副本");check(calls.find(c=>c.name==="hide")?.args.scope===scope&&!document.body.textContent?.includes("<img onerror=bad>"),"local hide failed");results.push("local hide binds selected scope and removes the copied body");
  reset();relayJobs=[{id,revision:5,source_revision:1,paused:false,cancel_requested:false,state:"staging",next:1,total:2}];receiving=[{id:target,revision:8,paused:false,abandoned:false,downloaded:1,total:2,expires_at:Date.now()+600000}];render();await sleep();await sleep();await click("暂停原中继后台");check(calls.find(c=>c.name==="pause")?.args.revision===5&&relayJobs[0].paused,"source pause loses revision/intent");await click("继续原中继后台");check(relayJobs[0].revision===7&&!relayJobs[0].paused,"source resume uses stale revision");results.push("background source pause and explicit resume retain the original job revision and authorization");
  confirmed=false;await click("放弃原历史暂存");check(!receiving[0].abandoned,"cancelled abandon removes progress");confirmed=true;await click("放弃原历史暂存");check(receiving[0].abandoned&&receiving[0].downloaded===0&&receiving[0].paused,"abandon does not retire partial ciphertext");await click("明确恢复原历史接收");check(!receiving[0].paused&&!receiving[0].abandoned&&receiving[0].revision===10,"receive resumed implicitly or lost revision");check(!calls.some(c=>c.name==="prepare"),"transfer controls create new grants");results.push("abandon confirmation clears only partial progress and requires explicit same-ID receive resume");
  reset();delay=true;render();await sleep();await sleep();check(finish,"snapshot not held");window.dispatchEvent(new Event("liteseal-device-paused"));finish!({targets,transfers:[]});await sleep();check(!document.querySelector('[aria-label="历史授权目标"]'),"late snapshot revived after pause");results.push("pause retires a delayed identity-bound snapshot");reset();return results;
};
(window as any).showHistoryTransfers=async()=>{reset();copies=[copied(),copied({id:"66666666-6666-4666-8666-666666666666",retracted:true,text:null})];render();await sleep();await sleep();document.querySelectorAll('details').forEach(d=>d.open=true);await choose();document.querySelectorAll('details').forEach(d=>d.open=true);};
