import {useEffect,useRef,useState} from "react";
import {getDesktopApi} from "../lib/desktopApi";
import {TransferredHistory} from "./TransferredHistory";
import type {CommandMap,DirectHistory} from "../../../electron/contracts";
type Snapshot=CommandMap["get_direct_history_transfers"]["result"];
type Intent=CommandMap["prepare_direct_history_transfer"]["args"];
export function HistoryTransfers({scope,account,originals,online,paused=false}:{scope:string;account:string;originals:DirectHistory["messages"];online:boolean;paused?:boolean}){
  const [view,setView]=useState<Snapshot|null>(null),[target,setTarget]=useState(""),[ids,setIds]=useState<string[]>([]),[includeMedia,setIncludeMedia]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(""),[status,setStatus]=useState("");
  const live=useRef(false),epoch=useRef(0),intent=useRef<Intent|null>(null);const [unknown,setUnknown]=useState(false);
  const valid=(n:number)=>live.current&&epoch.current===n&&!paused;
  async function refresh(){const n=epoch.current;try{const next=await getDesktopApi().get_direct_history_transfers({scope});if(valid(n)){setView(next);if(intent.current&&next.transfers.some(t=>t.id===intent.current!.id)){intent.current=null;setUnknown(false);}}}catch(e){if(valid(n))setError(String(e));}}
  useEffect(()=>{live.current=true;epoch.current++;setView(null);setTarget("");setIds([]);intent.current=null;setUnknown(false);setError("");setStatus("");setBusy(false);if(!paused)void refresh();const stop=()=>{epoch.current++;setView(null);setIds([]);intent.current=null;setUnknown(false);setBusy(false);setStatus("");};window.addEventListener("liteseal-device-paused",stop);window.addEventListener("liteseal-app-locked",stop);return()=>{live.current=false;epoch.current++;window.removeEventListener("liteseal-device-paused",stop);window.removeEventListener("liteseal-app-locked",stop);};},[scope,account,paused]);
  async function run(work:()=>Promise<unknown>){const n=epoch.current;if(busy||paused)return;setBusy(true);setError("");try{const result=await work();if(valid(n)){if(typeof result==="string")setStatus(result);await refresh();window.dispatchEvent(new Event("liteseal-history-transferred"));}}catch(e){if(valid(n)){setError(String(e));await refresh();}}finally{if(valid(n))setBusy(false);}}
  useEffect(()=>{const changed=()=>{if(!paused)void refresh();};window.addEventListener("liteseal-direct-changed",changed);return()=>window.removeEventListener("liteseal-direct-changed",changed);},[scope,account,paused]);
  function pauseTransfer(id:string,revision:number,receive:boolean,nextPaused:boolean,abandon=false){void run(()=>getDesktopApi().set_direct_history_pause({scope,id,revision,receive,paused:nextPaused,abandon}));}
  async function prepare(){if(!intent.current){if(!window.confirm(`将此会话中明确选定的 ${ids.length} 条消息授权给设备 ${target}？新设备须在 10 分钟内导入。`))return;intent.current={scope,id:crypto.randomUUID(),account,target,selection:[...ids],createdAt:Date.now(),includeMedia};setUnknown(true);}const saved=intent.current;await run(()=>getDesktopApi().prepare_direct_history_transfer(saved));}
  async function relay(id:string,revision:number){const n=epoch.current;await run(async()=>{for(let step=0;step<132&&valid(n);step++){const progress=await getDesktopApi().direct_history_relay_step({scope,id,revision});if(!valid(n))return;setStatus(`原授权中继 · ${progress.state} · ${progress.next} 块`);if(progress.state!=="staging")return progress.state==="ready"?"原授权已就绪，请在目标设备接收。":progress.state==="permitted"?"目标已取得导入许可；这不表示本机历史已保存。":progress.state==="received"?"目标已签名确认导入。":"原授权中继已终止，请查看原状态。";}throw new Error("原授权传输尚未完成，请沿原编号继续。");});}
  async function receive(){const n=epoch.current;await run(async()=>{for(let step=0;step<132&&valid(n);step++){const progress=await getDesktopApi().receive_direct_history_relay({scope});if(!valid(n))return;if(!progress.id)return "当前没有可接收的中继历史授权。";setStatus(`历史收件 · ${progress.downloaded}/${progress.total} 块`);if(progress.imported)return "已验证并导入原设备授权历史。";}throw new Error("原收件尚未完成，请继续接收。");});}
  const eligible=originals.filter(r=>r.peer===account&&["processed","retracted"].includes(r.outcome));
  return <section aria-label="选定历史授权" style={{minWidth:0,overflowWrap:"anywhere"}}><details><summary>选择历史授权给可信设备</summary><p>加入设备默认没有旧历史。原设备明确选择单个会话中的消息，保留原证据和修订，并只向当前已授权的目标密钥加密。草稿、静音、待发、定时和 ACK 各自独立。</p>
    {view?.targets.length? <><label>目标可信设备<select aria-label="历史授权目标" value={target} disabled={busy||paused||unknown} onChange={e=>setTarget(e.target.value)}><option value="">选择当前授权设备</option>{view.targets.map(t=><option key={t.device} value={t.device}>{t.device}</option>)}</select></label>{view.targets.filter(t=>t.device===target).map(t=><details key={t.device}><summary>目标公钥指纹</summary><p>加密 {t.encryption_fingerprint}</p><p>签名 {t.signing_fingerprint}</p></details>)}
      <fieldset style={{minWidth:0}} disabled={busy||paused||unknown}><legend>选择当前已加载、已确认的历史（最多 64 条，可先加载更早历史）</legend>{eligible.map(r=><label key={r.id} style={{display:"block"}}><input type="checkbox" checked={ids.includes(r.id)} disabled={!ids.includes(r.id)&&ids.length>=64} onChange={e=>setIds(previous=>e.target.checked?[...previous,r.id]:previous.filter(id=>id!==r.id))}/>{r.retracted?"已撤回占位":r.media?.name??r.text?.slice(0,80)??r.id}</label>)}</fieldset>
      <label><input type="checkbox" checked={includeMedia} disabled={busy||paused||unknown} onChange={e=>setIncludeMedia(e.target.checked)}/>包含已下载完整且认证通过的媒体</label><button disabled={busy||paused||!online||!target||!ids.length||unknown} onClick={()=>void prepare()}>保存选定历史授权</button>
      {unknown&&<><p>原准备结果待确认 · 编号 {intent.current?.id}</p><button disabled={busy||paused||!online} onClick={()=>void prepare()}>查询或继续原历史准备</button></>}
    </>:<p>当前档案没有可授权的目标。仅原设备能创建历史授权，请先完成可信设备授权。</p>}
    <button disabled={busy||paused||!online} onClick={()=>void receive()}>接收原设备中继授权</button><button disabled={busy||paused||!online} onClick={()=>void run(()=>getDesktopApi().import_direct_history_transfer({scope}))}>从原设备导入授权文件</button><p>先核对迁移会话的联系人根指纹，再选择原设备生成的 .lhistory 文件。首次导入联网核对当前授权，之后可离线阅读。已开始的原编号传输可在后台继续；锁定或休眠时暂停，单纯准备文件不会上传。</p>
    <ul aria-label="历史中继任务">{view?.relay_jobs?.map(j=><li key={j.id}><p>{j.id} · {j.state} · {j.next}/{j.total} 块{j.paused?" · 已暂停":""}{j.cancel_requested?" · 正在确认取消":""}</p>{["staging","ready","permitted"].includes(j.state)&&<><button disabled={busy||paused} onClick={()=>pauseTransfer(j.id,j.revision,false,!j.paused)}>{j.paused?"继续原中继后台":"暂停原中继后台"}</button><button disabled={busy||paused||!online} onClick={()=>{if(window.confirm("取消原中继？已许可或导入的副本不能远程擦除。"))void run(()=>getDesktopApi().cancel_direct_history_relay({scope,id:j.id,revision:j.source_revision}));}}>确认原中继取消</button></>}</li>)}</ul>
    <ul aria-label="未完成历史接收">{view?.receiving?.map(r=><li key={r.id}><p>{r.id} · {r.downloaded}/{r.total} 块{r.abandoned?" · 已放弃暂存":r.paused?" · 已暂停":" · 后台继续"}</p><button disabled={busy||paused} onClick={()=>pauseTransfer(r.id,r.revision,true,!r.paused)}>{r.paused?"明确恢复原历史接收":"暂停原历史接收"}</button>{!r.abandoned&&<button disabled={busy||paused} onClick={()=>{if(window.confirm("放弃此编号的未完成暂存？已确认历史保持，明确恢复后才重新下载。"))pauseTransfer(r.id,r.revision,true,true,true);}}>放弃原历史暂存</button>}</li>)}</ul>
    <button disabled={busy||paused} onClick={()=>void refresh()}>刷新历史授权记录</button><ul>{view?.transfers.map(t=><li key={t.id}><p>{t.peer} · {t.selected} 条 · {t.state} · {t.id}</p><p>目标 {t.target_device} · 导入截止 {new Date(t.expires_at).toLocaleString()}</p>{t.state==="prepared"&&<><button disabled={busy||paused||!online} onClick={()=>void relay(t.id,t.revision)}>查询或继续原授权中继</button><button disabled={busy||paused||!online} onClick={()=>{if(window.confirm("取消尚未取得导入许可的中继授权？已许可或导入的副本不能远程擦除。"))void run(async()=>{const result=await getDesktopApi().cancel_direct_history_relay({scope,id:t.id,revision:t.revision});return `原授权中继 · ${result.state}`;});}}>取消原授权中继</button><button disabled={busy||paused||!online||Date.now()>=t.expires_at} onClick={()=>void run(()=>getDesktopApi().export_direct_history_transfer({scope,id:t.id,revision:t.revision}))}>保存原授权文件</button><button disabled={busy||paused} onClick={()=>{if(window.confirm("停止在本机导出原授权？这不会取消中继，请单独取消原授权中继。已复制文件在期限内仍可导入，已导入历史不能远程擦除。"))void run(()=>getDesktopApi().cancel_direct_history_transfer({scope,id:t.id,revision:t.revision}));}}>停止本机导出</button></>}</li>)}</ul>
  </details>{status&&<p role="status">{status}</p>}{error&&<p role="alert">{error}</p>}<TransferredHistory scope={scope} account={account} paused={paused}/></section>;
}
