// Generated by uniffi-bindgen-react-native
#include "react-native-liteseal.h"
#include "generated/liteseal_core.hpp"

namespace liteseal {
	using namespace facebook;

	uint8_t installRustCrate(jsi::Runtime &runtime, std::shared_ptr<react::CallInvoker> callInvoker) {
		NativeLitesealCore::registerModule(runtime, callInvoker);
		return true;
	}

	uint8_t cleanupRustCrate(jsi::Runtime &runtime) {
		return false;
	}
}